//
// Created by Morteza Ahmadi on 2020-02-07.
//

#ifndef SKY_RULETYPE_H
#define SKY_RULETYPE_H

#include <stdio.h>
enum class RuleType {
    START,  
    PROGRAM,
    CLASS_DECLARATIONS,
    CLASS_DECLARATION,
    OPTIONAL_INHERITS,
    MEMBER_DECLARATIONS,
    FUNCTION_DEFINITIONS,
    FUNCTION_DEFINITION,
    FUNCTION_SIGNATURE,
    FUNCTION_BODY,
    VISIBILITY,
    FUNCTION_OR_VARIABLE_DECLARATION,
    TYPE_NON_ID,
    VARIABLE_DECLARATION,
    FUNCTION_DECLARATION,
    RELATION_EXPRESSION,
    STATEMENT_BLOCK,
    STATEMENT_VARIABLE,
    EXPRESSION,
    ASSIGN_STATEMENT_OR_FUNCTION_CALL,
    STATEMENT_VARIABLE_OR_FUNCTION_CALL,
    INDICES,
    VARIABLE_EXT,
    FUNCTION_CALL_PARAMS,
    FUNCTION_CALL_EXT,
    ASSIGNMENT_OP,
    TYPE,
    ARRAY_DIMENSIONS,
    FUNCTION_PARAMS_TAILS,
    INHERITED_CLASSES,
    ARITH_EXPRESSION,
    COMPARE_OP,
    FUNCTION_PARAMS,
    TYPE_OR_VOID,
    FUNCTION_CALL_PARAMS_TAILS,
    FUNCTION_CALL_PARAMS_TAIL,
    VARIABLE_DECLARATIONS,
    ARRAY_SIZE,
    RELATION_EXPRESSION_OR_NULL,
    STATEMENT,
    STATEMENTS,
    TERM,
    RIGHT_REC_ARITH_EXPRESSION,
    ADD_OP,
    FUNCTION_SIGNATURE_NAMESPACE,
    FUNCTION_SIGNATURE_EXT,
    SIGN,
    INDEX,
    FACTOR,
    VARIABLE_OR_FUNCTION_CALL,
    VARIABLE_FUNCTION_CALL,
    FACTOR_VARIABLE,
    FACTOR_FUNCTION_CALL,
    RIGHT_REC_TERM,
    MULT_OP,
    OPTIONAL_INT,
    LOCAL_SCOPE,

};


#endif //SKY_RULETYPE_H
